### ISSUE TITLE
Stream loading

### ISSUE THREAD

**Issue by FabienHenon** [jsonkenl/xlsxir#68]
Hi,

Thank you for this module, this is working fine!

However, when I want to load very big files (more than 200K lines), on my staging server I have a crash due to low memory. Would you consider adding functions to parse the xlsx file with streams so that one can load data as he needs it?

In my use case, the final user can upload xlsx files to import contacts, so a stream version of the `extract` would be great to improve my performances and avoid crashes for very big files :)

**Comment by rhetzler** [comment]
Hi @FabienHenon others have had similar problems so this went into the module recently. Please take a look at Xlsxir.stream_list/3 and see if this fits your needs.

https://hexdocs.pm/xlsxir/Xlsxir.html#stream_list/3

**Comment by FabienHenon** [comment]
Thank you that is what I was looking for!

However, I don't know if it's coming from `xlsxir` or `Elixir/Erlang` but I still have a crash:

```
binary_alloc: Cannot reallocate 257779553 bytes of memory (of type "binary")
```

My source code is: 
```elixir
  try do
      %{rows: rows, errors: errors} =
        path
        |> Xlsxir.stream_list(index)
        |> Enum.take(rows_count)
        |> Enum.with_index
        |> Enum.reduce(%{rows: [], errors: []}, &convert_row_to_string/2)

      {:reply, {:ok, %{rows: Enum.reverse(rows), errors: errors}}, state}
    rescue
      _ -> {:reply, {:error, {:bad_file, "Invalid file"}}, state}
    end
```

I don't think this is coming from my `convert_row_to_string` as it is working fine for smaller files and it's not doing heavy staff, just converting cell data to string.

Also, I'm only `take`ing 10 rows, so the problem should not be the amount of data I'm trying to fetch.

The excel file I'm trying to load is really simple. It's a simple table with several columns (about 10 columns), no formulas, only text, numbers and dates. But the file contains more than 200K lines.

Do you have any idea where the problem can come from?

PS: It's working fine locally. I guess that's because I have more memory than my DO server, but I don't think it's normal to crash for a need of 200MB of data with an excel file with a size of 33MB :(

**Comment by jsonkenl** [comment]
Hi @FabienHenon. An `.xlsx` file is actually a compressed file (much like a `.zip`), so the contents are larger than the original file once extracted. `Xlsxir` allows you to stream the parsing functionality of the file, but the required `.xml` files contained within the `.xlsx` file have to be extracted to the file system in full so that they are available for parsing. There is room for optimization by limiting the extraction process to only the files needed by the request (i.e. only extract the worksheet you are parsing if the file contains multiple worksheets), but I don't think this would help your situation since it would still need to extract the full `.xml` file containing the 200k rows of data that your code is trying to parse from.

**Comment by FabienHenon** [comment]
Alright, thank you for this information. There is nothing I can do except adding more RAM to my machine :)

I'll close this issue
