### ISSUE TITLE
ETS process vs data structure

### ISSUE THREAD

**Issue by phunehehe** [jsonkenl/xlsxir#84]
(I'm new to Excel / Erlang / Elixir parsing so please bear with me if this doesn't make too much sense.)

In order to avoid having to sandwich my code between `Xlsxir.multi_extract` and `Xlsxir.close` everywhere, I'm planning to make a helper function that extracts a file, converts everything into some data structure (probably a 2 dimensional array), then closes the ETS process. Then nothing else will have to care about the ETS process anymore.

2 questions:

- Would this function be a nice to have in xlsxir?
- Why would you not use such a function? Is it because the typical use case involves more random access than batch processing?

**Comment by jsonkenl** [comment]
@phunehehe Thanks for the message. My apologies for the delayed response. When I created Xlsxir, my typical use case did involve more random access so that is why I left everything in an ETS process. You're welcome to create a process per your description to be added to the library. Let me know if you have any questions as you're putting it together. Thanks!
